### PR TITLE
Feat: Add timing function to consumer download

### PR DESCRIPTION
**Pull request by daminals**
Consumers need to be informed about the latency for certain producers so they can decide who is the best choice for them.
Add timing function to consumer download so the consumer will know the download time per chunk purchased.

### CODE REVIEW

**Review by ingrettable — APPROVED** [review]
Looks good to me!

**Review by andrewctam — APPROVED** [review]

**Review by xiej2520 — COMMENTED** [review]
Nitpick: `start` doesn't need type specifier and duration can be formatted with `{}` instead of `{:?}`, otherwise looks good.

**Review by devu1997 — APPROVED** [review]
LGTM

**Review by xiej2520 — APPROVED** [review]
Looks good to me

**Pull request merged**
